name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Push Image to Docker Hub
        run: docker push cygnetops/react-test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wait for build job to complete
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker pull cygnetops/react-test
            docker run -d -p 3000:3000 --name myapp cygnetops/react-test
